### PR TITLE
Remove vendor to keep less conflict with upstream.

### PR DESCRIPTION
**Pull request by xuezhaojun**

### CODE REVIEW

**Comment by zhujian7** [comment]
should we merge this in 2.9?

**Comment by xuezhaojun** [comment]
> should we merge this in 2.9?

I think it's good to go.

**Comment by zhujian7** [comment]
> > should we merge this in 2.9?
> 
> I think it's good to go. It's small enough to merge without impact other components or squad.

I am not quite sure about this, does the downstream build need to do some changes?

**Comment by xuezhaojun** [comment]
> > > should we merge this in 2.9?
> > 
> > 
> > I think it's good to go. It's small enough to merge without impact other components or squad.
> 
> I am not quite sure about this, does the downstream build need to do some changes?

That's a good question, I think I need to check the dockerfile on gitlab.

**Pull request closed without merging**
