### PR TITLE
update dockerfile image to go 1.18

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

https://github.com/stolostron/backlog/issues/22707

### CODE REVIEW

**Comment by skeeey** [comment]
@xuezhaojun it seems that build env has some problem

```
/go/src/github.com/stolostron/cluster-proxy/bin/controller-gen: No such file or directory
```

**Comment by xuezhaojun** [comment]
> @xuezhaojun it seems that build env has some problem
> 
> ```
> /go/src/github.com/stolostron/cluster-proxy/bin/controller-gen: No such file or directory
> ```

Yes, it Pr need to rebase after this upstream PR https://github.com/open-cluster-management-io/cluster-proxy/pull/123.

**Pull request merged**
