### PR TITLE
Add makefile.prow

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

### CODE REVIEW

**Comment by skeeey** [comment]
@xuezhaojun is it for build-harness (travis)? do we need it?

**Comment by xuezhaojun** [comment]
> @xuezhaojun is it for build-harness (travis)? do we need it?

I found `Makefile.prow` is related with `sonar scans` as the following document said, I think we don't need travis but how about sonar?

**Comment by xuezhaojun** [comment]
/hold 
If we don't need sonar scan, this PR would be closed.

**Pull request merged**
